### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by Ram-here** [kishan0725/AJAX-Movie-Recommendation-System-with-Sentiment-Analysis#2]
@kishan0725 An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by kishan0725** [comment]
@Ram-here This is not related to the application. There must be something that went wrong when deploying the application to heroku. 

And the error itself says `heroku logs --tail` to track the issue. So just run the heroku command in the CLI. Before that, verify whether the app is running in your local machine. If the app is running perfectly fine in your local machine, there should be an issue with your deployment. If it's not running in the local machine as well, then please go through the closed issue to see if that helps you to resolve the issue. If your error is something different from the closed issues, then please create a separate issue with detailed explanation of your issue.

**Comment by kishan0725** [comment]
@Ram-here Sorry, just now I came to know that this is the error in my app. I just see the logs and it's because I've my running time quota exhausted since I'm using free-tier. I've exhausted my 550 hours allocated for the month of December 2020. So, the app will be back to its working state on January 1, 2021. Thank you!
